name: atalantify
description: Spotify connect transfer from shortcuts.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.10
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  flutter_riverpod: ^0.12.3
  hooks_riverpod: ^0.12.3
  riverpod: ^0.12.3
  flutter_webview_plugin: ^0.3.11
  freezed_annotation: ^0.12.0
  fluttertoast: ^7.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0
  pedantic: ^1.8.0
  json_serializable:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
