name: atalantify
description: Spotify support application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  json_annotation: ^3.0.0
  share: ^0.6.2+1
  provider: ^3.1.0
  quick_actions: ^0.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.2
  build_runner: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
